// Curated list of notable U.S. federal contractors for the search type-ahead.
// Sourced from the Wikipedia "Top 100 Contractors of the U.S. federal government",
// Washington Technology Top 100, and well-known primes. `name` is the canonical query
// sent to Tako; `aliases` are extra strings the fuzzy matcher also searches (tickers,
// former/common names). Pure data — no Tako calls. Extend freely.

export interface Company {
  name: string;
  aliases?: string[];
}

export const COMPANIES: Company[] = [
  { name: "Lockheed Martin", aliases: ["LMT", "Lockheed"] },
  { name: "RTX", aliases: ["Raytheon", "RTX Corporation", "Raytheon Technologies", "RTN"] },
  { name: "General Dynamics", aliases: ["GD"] },
  { name: "The Boeing Company", aliases: ["Boeing", "BA"] },
  { name: "Northrop Grumman", aliases: ["NOC", "Northrop"] },
  { name: "Leidos", aliases: ["LDOS", "SAIC Leidos"] },
  { name: "L3Harris Technologies", aliases: ["L3Harris", "LHX", "Harris", "L3"] },
  { name: "BAE Systems", aliases: ["BAE"] },
  { name: "Booz Allen Hamilton", aliases: ["Booz Allen", "BAH"] },
  { name: "Humana", aliases: ["HUM"] },
  { name: "Huntington Ingalls Industries", aliases: ["Huntington Ingalls", "HII", "Newport News"] },
  { name: "General Electric", aliases: ["GE", "GE Aerospace"] },
  { name: "Science Applications International Corporation", aliases: ["SAIC"] },
  { name: "Accenture", aliases: ["Accenture Federal Services", "ACN"] },
  { name: "Deloitte", aliases: ["Deloitte Consulting"] },
  { name: "Pfizer", aliases: ["PFE"] },
  { name: "McKesson", aliases: ["MCK"] },
  { name: "AmerisourceBergen", aliases: ["Cencora", "ABC"] },
  { name: "CACI International", aliases: ["CACI"] },
  { name: "Peraton" },
  { name: "Amentum" },
  { name: "Jacobs", aliases: ["Jacobs Solutions", "J"] },
  { name: "KBR", aliases: ["Kellogg Brown Root"] },
  { name: "Bechtel" },
  { name: "Fluor", aliases: ["FLR"] },
  { name: "Honeywell", aliases: ["HON", "Honeywell International"] },
  { name: "Microsoft", aliases: ["MSFT"] },
  { name: "Amazon", aliases: ["Amazon Web Services", "AWS", "AMZN"] },
  { name: "Google", aliases: ["Alphabet", "Google Public Sector", "GOOGL"] },
  { name: "Oracle", aliases: ["ORCL"] },
  { name: "Dell Technologies", aliases: ["Dell", "DELL"] },
  { name: "IBM", aliases: ["International Business Machines"] },
  { name: "Palantir Technologies", aliases: ["Palantir", "PLTR"] },
  { name: "Anduril Industries", aliases: ["Anduril"] },
  { name: "SpaceX", aliases: ["Space Exploration Technologies"] },
  { name: "Tesla", aliases: ["TSLA"] },
  { name: "AT&T", aliases: ["ATT", "T"] },
  { name: "Verizon", aliases: ["VZ"] },
  { name: "ManTech International", aliases: ["ManTech"] },
  { name: "ICF International", aliases: ["ICF"] },
  { name: "Maximus", aliases: ["MMS"] },
  { name: "Guidehouse" },
  { name: "Parsons Corporation", aliases: ["Parsons", "PSN"] },
  { name: "Textron", aliases: ["TXT", "Bell", "Textron Aviation"] },
  { name: "United Launch Alliance", aliases: ["ULA"] },
  { name: "Raytheon Intelligence & Space" },
  { name: "Pratt & Whitney" },
  { name: "Collins Aerospace" },
  { name: "Cardinal Health", aliases: ["CAH"] },
  { name: "CVS Health", aliases: ["CVS", "Aetna"] },
  { name: "UnitedHealth Group", aliases: ["UnitedHealth", "Optum", "UNH"] },
  { name: "Centene", aliases: ["CNC"] },
  { name: "Moderna", aliases: ["MRNA"] },
  { name: "Johnson & Johnson", aliases: ["JNJ", "Janssen"] },
  { name: "Merck", aliases: ["MRK"] },
  { name: "FedEx", aliases: ["FDX"] },
  { name: "UPS", aliases: ["United Parcel Service"] },
  { name: "Boeing Defense, Space & Security", aliases: ["Boeing Defense"] },
  { name: "Sierra Nevada Corporation", aliases: ["Sierra Nevada", "SNC"] },
  { name: "Cisco Systems", aliases: ["Cisco", "CSCO"] },
  { name: "Hewlett Packard Enterprise", aliases: ["HPE"] },
  { name: "ASRC Federal" },
  { name: "Leidos QTC Health Services", aliases: ["QTC"] },
  { name: "Battelle" },
  { name: "MITRE", aliases: ["MITRE Corporation"] },
  { name: "Aerospace Corporation" },
  { name: "Johns Hopkins University Applied Physics Laboratory", aliases: ["APL", "Johns Hopkins APL"] },
  { name: "SAIC", aliases: ["Science Applications International"] },
  { name: "GDIT", aliases: ["General Dynamics Information Technology"] },
  { name: "Vectrus" },
  { name: "V2X", aliases: ["V2X Inc"] },
  { name: "DXC Technology", aliases: ["DXC"] },
  { name: "Unisys", aliases: ["UIS"] },
  { name: "Carahsoft" },
  { name: "World Wide Technology", aliases: ["WWT"] },
  { name: "Leonardo DRS", aliases: ["DRS"] },
  { name: "Elbit Systems of America", aliases: ["Elbit"] },
  { name: "General Atomics" },
  { name: "Rolls-Royce North America", aliases: ["Rolls-Royce"] },
];
